/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.testmaven.views;

import com.test.testmaven.bean.MenuListBean;
import com.test.testmaven.controller.ChangeWindowNhapXuatController;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class MenuNhapXuatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhapXuatJPanel
     */
    public MenuNhapXuatJPanel() {
        initComponents();
        
        ChangeWindowNhapXuatController controller = new ChangeWindowNhapXuatController(jpnView);
        List<MenuListBean> listItem = new ArrayList<>();
        listItem.add(new MenuListBean("PhieuNhap", jpnPhieuNhap, jlbPhieuNhap));
        listItem.add(new MenuListBean("ChiTietPhieuNhap", jpnChiTietPhieuNhap, jlbChiTietPhieuNhap));
        listItem.add(new MenuListBean("PhieuXuat", jpnPhieuXuat, jlbPhieuXuat));
        listItem.add(new MenuListBean("ChiTietPhieuXuat", jpnChiTietPhieuXuat, jlbChiTietPhieuXuat));
        controller.setEven(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnPhieuNhap = new javax.swing.JPanel();
        jlbPhieuNhap = new javax.swing.JLabel();
        jpnChiTietPhieuNhap = new javax.swing.JPanel();
        jlbChiTietPhieuNhap = new javax.swing.JLabel();
        jpnChiTietPhieuXuat = new javax.swing.JPanel();
        jlbChiTietPhieuXuat = new javax.swing.JLabel();
        jpnPhieuXuat = new javax.swing.JPanel();
        jlbPhieuXuat = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        jpnRoot.setBackground(new java.awt.Color(153, 153, 0));

        jpnPhieuNhap.setBackground(new java.awt.Color(153, 255, 255));
        jpnPhieuNhap.setPreferredSize(new java.awt.Dimension(300, 200));

        jlbPhieuNhap.setBackground(new java.awt.Color(0, 0, 0));
        jlbPhieuNhap.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlbPhieuNhap.setForeground(new java.awt.Color(0, 0, 0));
        jlbPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_article_black_18dp.png"))); // NOI18N
        jlbPhieuNhap.setText("Phiếu nhập");

        javax.swing.GroupLayout jpnPhieuNhapLayout = new javax.swing.GroupLayout(jpnPhieuNhap);
        jpnPhieuNhap.setLayout(jpnPhieuNhapLayout);
        jpnPhieuNhapLayout.setHorizontalGroup(
            jpnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhieuNhapLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlbPhieuNhap)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jpnPhieuNhapLayout.setVerticalGroup(
            jpnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhieuNhapLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbPhieuNhap)
                .addGap(30, 30, 30))
        );

        jpnChiTietPhieuNhap.setBackground(new java.awt.Color(153, 255, 255));
        jpnChiTietPhieuNhap.setPreferredSize(new java.awt.Dimension(300, 200));

        jlbChiTietPhieuNhap.setBackground(new java.awt.Color(0, 0, 0));
        jlbChiTietPhieuNhap.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlbChiTietPhieuNhap.setForeground(new java.awt.Color(0, 0, 0));
        jlbChiTietPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_wifi_protected_setup_black_18dp.png"))); // NOI18N
        jlbChiTietPhieuNhap.setText("Chi tiết phiếu nhập");

        javax.swing.GroupLayout jpnChiTietPhieuNhapLayout = new javax.swing.GroupLayout(jpnChiTietPhieuNhap);
        jpnChiTietPhieuNhap.setLayout(jpnChiTietPhieuNhapLayout);
        jpnChiTietPhieuNhapLayout.setHorizontalGroup(
            jpnChiTietPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChiTietPhieuNhapLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlbChiTietPhieuNhap)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jpnChiTietPhieuNhapLayout.setVerticalGroup(
            jpnChiTietPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChiTietPhieuNhapLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbChiTietPhieuNhap)
                .addGap(30, 30, 30))
        );

        jpnChiTietPhieuXuat.setBackground(new java.awt.Color(153, 255, 255));
        jpnChiTietPhieuXuat.setPreferredSize(new java.awt.Dimension(300, 200));

        jlbChiTietPhieuXuat.setBackground(new java.awt.Color(0, 0, 0));
        jlbChiTietPhieuXuat.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlbChiTietPhieuXuat.setForeground(new java.awt.Color(0, 0, 0));
        jlbChiTietPhieuXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_agriculture_black_18dp.png"))); // NOI18N
        jlbChiTietPhieuXuat.setText("Chi tiết phiếu xuất");

        javax.swing.GroupLayout jpnChiTietPhieuXuatLayout = new javax.swing.GroupLayout(jpnChiTietPhieuXuat);
        jpnChiTietPhieuXuat.setLayout(jpnChiTietPhieuXuatLayout);
        jpnChiTietPhieuXuatLayout.setHorizontalGroup(
            jpnChiTietPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChiTietPhieuXuatLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlbChiTietPhieuXuat)
                .addGap(119, 119, 119))
        );
        jpnChiTietPhieuXuatLayout.setVerticalGroup(
            jpnChiTietPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChiTietPhieuXuatLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbChiTietPhieuXuat)
                .addGap(30, 30, 30))
        );

        jpnPhieuXuat.setBackground(new java.awt.Color(153, 255, 255));
        jpnPhieuXuat.setPreferredSize(new java.awt.Dimension(300, 200));

        jlbPhieuXuat.setBackground(new java.awt.Color(0, 0, 0));
        jlbPhieuXuat.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlbPhieuXuat.setForeground(new java.awt.Color(0, 0, 0));
        jlbPhieuXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_article_black_18dp.png"))); // NOI18N
        jlbPhieuXuat.setText("Phiếu xuất");

        javax.swing.GroupLayout jpnPhieuXuatLayout = new javax.swing.GroupLayout(jpnPhieuXuat);
        jpnPhieuXuat.setLayout(jpnPhieuXuatLayout);
        jpnPhieuXuatLayout.setHorizontalGroup(
            jpnPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhieuXuatLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlbPhieuXuat)
                .addGap(176, 176, 176))
        );
        jpnPhieuXuatLayout.setVerticalGroup(
            jpnPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhieuXuatLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbPhieuXuat)
                .addGap(30, 30, 30))
        );

        jpnView.setBackground(new java.awt.Color(102, 255, 255));
        jpnView.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnChiTietPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnChiTietPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jpnPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnChiTietPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnChiTietPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 188, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbChiTietPhieuNhap;
    private javax.swing.JLabel jlbChiTietPhieuXuat;
    private javax.swing.JLabel jlbPhieuNhap;
    private javax.swing.JLabel jlbPhieuXuat;
    private javax.swing.JPanel jpnChiTietPhieuNhap;
    private javax.swing.JPanel jpnChiTietPhieuXuat;
    private javax.swing.JPanel jpnPhieuNhap;
    private javax.swing.JPanel jpnPhieuXuat;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
