package com.test.testmaven.views;

import com.test.testmaven.bean.MenuListBean;
import com.test.testmaven.controller.ChangeWindowDonDhController;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class MenuDonDhJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonDhJPanel
     */
    public MenuDonDhJPanel() {
        initComponents();
        
        ChangeWindowDonDhController controller = new ChangeWindowDonDhController(jpnView);
        List<MenuListBean> listItem = new ArrayList<>();
        listItem.add(new MenuListBean("DonDh", jpnDonDh, jlbDonDh));
        listItem.add(new MenuListBean("ChiTietDonDatHang", jpnCTDonDh, jlbCTDonDh));
        controller.setEven(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnDonDh = new javax.swing.JPanel();
        jlbDonDh = new javax.swing.JLabel();
        jpnCTDonDh = new javax.swing.JPanel();
        jlbCTDonDh = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        jpnRoot.setBackground(new java.awt.Color(255, 255, 102));

        jpnDonDh.setBackground(new java.awt.Color(153, 153, 255));
        jpnDonDh.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jpnDonDh.setPreferredSize(new java.awt.Dimension(300, 200));

        jlbDonDh.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlbDonDh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_article_black_18dp.png"))); // NOI18N
        jlbDonDh.setText("Đơn đặt hàng");

        javax.swing.GroupLayout jpnDonDhLayout = new javax.swing.GroupLayout(jpnDonDh);
        jpnDonDh.setLayout(jpnDonDhLayout);
        jpnDonDhLayout.setHorizontalGroup(
            jpnDonDhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDonDhLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlbDonDh)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jpnDonDhLayout.setVerticalGroup(
            jpnDonDhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDonDhLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlbDonDh)
                .addGap(40, 40, 40))
        );

        jpnCTDonDh.setBackground(new java.awt.Color(153, 153, 255));
        jpnCTDonDh.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jpnCTDonDh.setPreferredSize(new java.awt.Dimension(300, 200));

        jlbCTDonDh.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlbCTDonDh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_view_list_black_18dp.png"))); // NOI18N
        jlbCTDonDh.setText("Chi tiết đơn đặt hàng");

        javax.swing.GroupLayout jpnCTDonDhLayout = new javax.swing.GroupLayout(jpnCTDonDh);
        jpnCTDonDh.setLayout(jpnCTDonDhLayout);
        jpnCTDonDhLayout.setHorizontalGroup(
            jpnCTDonDhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCTDonDhLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlbCTDonDh)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jpnCTDonDhLayout.setVerticalGroup(
            jpnCTDonDhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCTDonDhLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlbCTDonDh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jpnView.setBackground(new java.awt.Color(102, 255, 255));
        jpnView.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnCTDonDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnDonDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jpnDonDh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpnCTDonDh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 350, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbCTDonDh;
    private javax.swing.JLabel jlbDonDh;
    private javax.swing.JPanel jpnCTDonDh;
    private javax.swing.JPanel jpnDonDh;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
